# Generated by Django 2.1 on 2018-09-13 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=20, verbose_name='商品名称')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格')),
                ('gdesc', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品介绍')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('img', models.ImageField(upload_to='goodsimg')),
            ],
            options={
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='TypeGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='种类')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.TypeGoods'),
        ),
    ]
